In [36]:
import torch.nn as nn
import torch

In [37]:
# INPUT (temp , rainfall , humidity)
import numpy as np
import torch
inputs = np.array([[23,34,56],[67,78,89],[98,76,65],    
                   [32,43,54],[65,76,87],[98,84,76],
                   [63,74,85],[19,82,73],[65,74,83],
                   [34,35,36],[37,38,39],[32,31,30],
                   [29,28,26],[56,53,55],[44,68,93]],dtype='float32')

#targets(apples , oranges)
targets = np.array([[54,89],[84,43],[86,59],
                   [22,34],[34,98],[65,45],
                   [14,95],[39,89],[34,98],
                   [56,90],[19,45],[61,12],
                   [12,23],[34,45],[56,67]],dtype='float32')
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)
targets.shape

tensor([[23., 34., 56.],
        [67., 78., 89.],
        [98., 76., 65.],
        [32., 43., 54.],
        [65., 76., 87.],
        [98., 84., 76.],
        [63., 74., 85.],
        [19., 82., 73.],
        [65., 74., 83.],
        [34., 35., 36.],
        [37., 38., 39.],
        [32., 31., 30.],
        [29., 28., 26.],
        [56., 53., 55.],
        [44., 68., 93.]])
tensor([[54., 89.],
        [84., 43.],
        [86., 59.],
        [22., 34.],
        [34., 98.],
        [65., 45.],
        [14., 95.],
        [39., 89.],
        [34., 98.],
        [56., 90.],
        [19., 45.],
        [61., 12.],
        [12., 23.],
        [34., 45.],
        [56., 67.]])


torch.Size([15, 2])

In [38]:
#DATASET AND DATALOADER
from torch.utils.data import TensorDataset  # here we create a tensordataset which gives access to rows from inputs and targets as tuples
#and provide standard APIs for working with many different types of datasets in pytorch


In [39]:
#DEFINE DATASET

train_ds = TensorDataset(inputs , targets)
train_ds[0:3]  # here we get the access for a small section of the training data from th entire dataset, by indexing.

(tensor([[23., 34., 56.],
         [67., 78., 89.],
         [98., 76., 65.]]),
 tensor([[54., 89.],
         [84., 43.],
         [86., 59.]]))

In [40]:
train_ds = TensorDataset(inputs , targets)
train_ds[0:4, 0:2] 

(tensor([[23., 34.],
         [67., 78.],
         [98., 76.],
         [32., 43.]]),
 tensor([[54., 89.],
         [84., 43.],
         [86., 59.],
         [22., 34.]]))

In [41]:
#DATALOADER 
from torch.utils.data import DataLoader
#here it splits the dataset into batches of predefined size while training, it also provides shuffling and rndom sampling of data

In [42]:
batch_size = 5
train_d1 = DataLoader(train_ds, batch_size, shuffle=True)

In [43]:
for xb,yb in train_d1:   # there are three batches in input and three batches in targets.from 6 batches we are getting only two
    print(xb)
    print(yb)
    break
    #returns one batch of data gives five rows of data

tensor([[19., 82., 73.],
        [23., 34., 56.],
        [65., 76., 87.],
        [63., 74., 85.],
        [56., 53., 55.]])
tensor([[39., 89.],
        [54., 89.],
        [34., 98.],
        [14., 95.],
        [34., 45.]])


In [44]:
#FOR VIEWING ALL BATCHES
for xb,yb in train_d1:
    print('batch:')
    print(xb)
    print(yb)
    #break
    #returns one batch of data gives five rows of data


batch:
tensor([[32., 31., 30.],
        [44., 68., 93.],
        [67., 78., 89.],
        [65., 76., 87.],
        [37., 38., 39.]])
tensor([[61., 12.],
        [56., 67.],
        [84., 43.],
        [34., 98.],
        [19., 45.]])
batch:
tensor([[19., 82., 73.],
        [65., 74., 83.],
        [98., 76., 65.],
        [34., 35., 36.],
        [29., 28., 26.]])
tensor([[39., 89.],
        [34., 98.],
        [86., 59.],
        [56., 90.],
        [12., 23.]])
batch:
tensor([[23., 34., 56.],
        [32., 43., 54.],
        [56., 53., 55.],
        [98., 84., 76.],
        [63., 74., 85.]])
tensor([[54., 89.],
        [22., 34.],
        [34., 45.],
        [65., 45.],
        [14., 95.]])


In [45]:
#nn.LINEAR method , here we dont want to give values to the weights , all are take care by the nn.linear method.
#DEFINE MODEL

model = nn.Linear(3, 2)#(inputs , outputs)([temp,rainfall,humidity],[apple_yield,orange_yield])
print(model.weight)# creates weight
print(model.bias)

Parameter containing:
tensor([[ 0.4722, -0.1550, -0.3560],
        [ 0.2022, -0.1082, -0.2511]], requires_grad=True)
Parameter containing:
tensor([-0.2103,  0.2612], requires_grad=True)


In [46]:
#PARAMETERS
list(model.parameters())

[Parameter containing:
 tensor([[ 0.4722, -0.1550, -0.3560],
         [ 0.2022, -0.1082, -0.2511]], requires_grad=True),
 Parameter containing:
 tensor([-0.2103,  0.2612], requires_grad=True)]

In [47]:
#GENERATE PREDICTIONS
preds = model(inputs)
preds

tensor([[-14.5551, -12.8303],
        [-12.3464, -16.9829],
        [ 11.1444,  -4.4730],
        [-10.9884, -11.4824],
        [-12.2688, -16.6685],
        [  5.9887,  -8.1008],
        [-12.1912, -16.3542],
        [-29.9340, -23.1010],
        [-10.5349, -15.4477],
        [ -2.3964,  -5.6925],
        [ -2.5128,  -6.1640],
        [ -0.5849,  -4.1573],
        [ -0.1125,  -3.4348],
        [ -1.5622,  -7.9638],
        [-23.0804, -21.5549]], grad_fn=<AddmmBackward0>)

In [48]:
#LOSS FUNCTION
#instead defining the loss manually we can use built-in loss function mse_loss

#import nn.functional
import torch.nn.functional as F

In [49]:
#defining loss function
loss_fn = F.mse_loss

In [50]:
?nn.Linear   # shows the documentation

Object `nn.Linear   # shows the documentation` not found.


In [51]:
?F.mse_loss  # shows documentation 

Object `F.mse_loss  # shows documentation` not found.


In [52]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(4876.7031, grad_fn=<MseLossBackward0>)


In [53]:
#OPTIMIZER

In [54]:
#define optimizer 
opt = torch.optim.SGD(model.parameters(), lr=1e-5)   #SGD = stochastic gradient descent
#model.parameters() is passed as an argument for the optim.SGD .so that the optimizer knows which matrices should be modified 
#during update step. also lr= learning rate which controls the amount by which the parameters are modified.

In [55]:
#TRAIN THE MODEL

#UTILITY FUNCTION TO TRAIN THE MODEL

def fit(num_epochs , model , loss_fn , opt):
    #repeat for give nnumber of epochs
    for epoch in range(num_epochs):
        #train with batches of data 
        for xb , yb in train_d1:
            
            #1.)generate predictions
            pred = model(xb)  # xb = inputs
            
            #2.) calculate loss
            loss = loss_fn(pred, yb)  # yb = targets
            
            #3.) compute gradient
            loss.backward()
            
            #4.) update parameters using gradient
            opt.step()
            
            #5.) reset the gradient to zero
            opt.zero_grad()
        
        #print the progress
        if(epoch+1) % 10 ==0:
            print('epoch [{}/{}], loss:{:.4f}' .format(epoch+1, num_epochs , loss.item()))       

In [56]:
fit(100 , model , loss_fn , opt)   # we get loss decreased value from 3027 to 341 using epochs.

epoch [10/100], loss:759.8840
epoch [20/100], loss:1055.4526
epoch [30/100], loss:780.7430
epoch [40/100], loss:488.1837
epoch [50/100], loss:746.9366
epoch [60/100], loss:920.2512
epoch [70/100], loss:425.6279
epoch [80/100], loss:405.1440
epoch [90/100], loss:709.3325
epoch [100/100], loss:295.0332


In [57]:
preds=model(inputs)
preds

tensor([[21.8431, 45.3217],
        [55.9439, 81.7827],
        [71.6384, 68.0623],
        [28.2709, 47.8912],
        [54.3626, 79.8460],
        [73.6296, 77.3620],
        [52.7812, 77.9094],
        [28.4641, 73.6835],
        [53.7866, 76.8228],
        [26.9722, 34.7116],
        [29.3442, 37.6166],
        [24.8149, 29.7517],
        [22.3804, 26.2880],
        [43.5275, 52.7616],
        [41.5653, 79.7210]], grad_fn=<AddmmBackward0>)

In [58]:
targets  # prediction is pretty close to the actual values 

tensor([[54., 89.],
        [84., 43.],
        [86., 59.],
        [22., 34.],
        [34., 98.],
        [65., 45.],
        [14., 95.],
        [39., 89.],
        [34., 98.],
        [56., 90.],
        [19., 45.],
        [61., 12.],
        [12., 23.],
        [34., 45.],
        [56., 67.]])

In [59]:
model(torch.tensor([[75, 63, 44.]]))
#it gives more probability to oranges than the apple for the given input conditions , so the yield is orange.

tensor([[55.2073, 50.8511]], grad_fn=<AddmmBackward0>)